on:
    push:
        branches:
            - master





jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "printing"
        run: echo sondos
      - name: "login"
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
      - name: "build img"
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/yyy .    
      - name: "push img"
        run: docker push ${{secrets.DOCKER_USERNAME}}/yyy
    





            
